# This file is distributed under the same license as the Django package.
#
# Translators:
# Bayarkhuu Bataa, 2017
# Jannis Leidel <jannis@leidel.info>, 2011
# Zorig <zorig_ezd@yahoo.com>, 2014
# Анхбаяр Анхаа <l.ankhbayar@gmail.com>, 2011-2012
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-09-07 17:12+0800\n"
"PO-Revision-Date: 2017-10-19 14:01+0000\n"
"Last-Translator: Bayarkhuu Bataa\n"
"Language-Team: Mongolian (http://www.transifex.com/django/django/language/"
"mn/)\n"
"Language: mn\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: horizon_env/lib/python3.8/site-packages/django/contrib/contenttypes/apps.py:16
msgid "Content Types"
msgstr "Агуулгын төрөл"

#: horizon_env/lib/python3.8/site-packages/django/contrib/contenttypes/models.py:135
msgid "python model class name"
msgstr "пайтоны моделын классын нэр"

#: horizon_env/lib/python3.8/site-packages/django/contrib/contenttypes/models.py:139
msgid "content type"
msgstr "агуулгын төрөл"

#: horizon_env/lib/python3.8/site-packages/django/contrib/contenttypes/models.py:140
msgid "content types"
msgstr "агуулгын төрлүүд"

#: horizon_env/lib/python3.8/site-packages/django/contrib/contenttypes/views.py:18
#, python-format
msgid "Content type %(ct_id)s object has no associated model"
msgstr "%(ct_id)s төрлийн холбоотой модель олдсонгүй"

#: horizon_env/lib/python3.8/site-packages/django/contrib/contenttypes/views.py:24
#, fuzzy, python-format
#| msgid "Content type %(ct_id)s object %(obj_id)s doesn't exist"
msgid "Content type %(ct_id)s object %(obj_id)s doesn’t exist"
msgstr "%(ct_id)s төрлийн %(obj_id)s объект олдсонгүй"

#: horizon_env/lib/python3.8/site-packages/django/contrib/contenttypes/views.py:32
#, fuzzy, python-format
#| msgid "%(ct_name)s objects don't have a get_absolute_url() method"
msgid "%(ct_name)s objects don’t have a get_absolute_url() method"
msgstr ""
"%(ct_name)s объектууд дээр get_absolute_url() функцийг тодорхойлоогүй байна."
